site_name: Nutrio Documentation
site_url: https://liena-grytsyna.github.io/nutrio/

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - System Overview: system-overview.md
  - API: api.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material